/**
 * Project gallery data. Drives the filterable Gallery page, the before/after
 * sliders, the homepage "featured work" strip, and ImageObject JSON-LD.
 *
 * Images are tasteful SVG placeholders generated by
 * `scripts/generate-placeholders.mjs` with keyword-rich filenames. Replace the
 * files in /public/images/gallery with real project photos (.jpg/.webp) when
 * the client supplies them — keep the descriptive filenames for image SEO.
 */

export type GalleryCategory = {
  slug: string;
  label: string;
};

export const galleryCategories: GalleryCategory[] = [
  { slug: "all", label: "All Projects" },
  { slug: "tree-removal", label: "Tree Removal" },
  { slug: "stump-grinding", label: "Stump Grinding" },
  { slug: "mulching", label: "Mulching" },
  { slug: "landscape-design", label: "Landscape Design" },
  { slug: "cleanup", label: "Cleanups" },
];

export type GalleryImage = {
  src: string;
  /** Keyword-rich, descriptive alt text (image SEO + accessibility). */
  alt: string;
  width: number;
  height: number;
};

export type GalleryItem = {
  id: string;
  title: string;
  category: Exclude<GalleryCategory["slug"], "all">;
  location: string;
  description: string;
  /** A before/after pair renders a comparison slider; otherwise a single image. */
  before?: GalleryImage;
  after: GalleryImage;
  featured?: boolean;
};

const W = 1200;
const H = 800;

export const galleryItems: GalleryItem[] = [
  {
    id: "tree-removal-west-bethlehem",
    title: "Large Tree Removal in West Bethlehem",
    category: "tree-removal",
    location: "Bethlehem, PA",
    description:
      "Safe removal of a large, declining tree close to the home, with full debris cleanup.",
    before: {
      src: "/images/gallery/tree-removal-bethlehem-pa-before.svg",
      alt: "Large overgrown tree before removal at a Bethlehem PA home",
      width: W,
      height: H,
    },
    after: {
      src: "/images/gallery/tree-removal-bethlehem-pa-after.svg",
      alt: "Clean, open yard after professional tree removal in Bethlehem PA",
      width: W,
      height: H,
    },
    featured: true,
  },
  {
    id: "stump-grinding-lehigh-valley",
    title: "Stump Grinding in the Lehigh Valley",
    category: "stump-grinding",
    location: "Lehigh Valley, PA",
    description:
      "Old stump ground below grade and cleaned up, ready for grass and new plantings.",
    before: {
      src: "/images/gallery/stump-grinding-lehigh-valley-before.svg",
      alt: "Old tree stump before grinding in the Lehigh Valley",
      width: W,
      height: H,
    },
    after: {
      src: "/images/gallery/stump-grinding-lehigh-valley-after.svg",
      alt: "Level ground after stump grinding in the Lehigh Valley, ready to reseed",
      width: W,
      height: H,
    },
    featured: true,
  },
  {
    id: "mulching-14-yards-bethlehem",
    title: "14 Yards of Fresh Mulch in Bethlehem",
    category: "mulching",
    location: "Bethlehem, PA",
    description:
      "Old shrubs removed and 14 yards of fresh mulch installed across newly edged beds.",
    before: {
      src: "/images/gallery/mulching-bethlehem-pa-before.svg",
      alt: "Tired plant beds before fresh mulch installation in Bethlehem PA",
      width: W,
      height: H,
    },
    after: {
      src: "/images/gallery/mulching-bethlehem-pa-after.svg",
      alt: "Freshly mulched and edged garden beds after mulching in Bethlehem PA",
      width: W,
      height: H,
    },
    featured: true,
  },
  {
    id: "landscape-design-front-yard-bethlehem",
    title: "Front Yard Landscape Design in Bethlehem",
    category: "landscape-design",
    location: "Bethlehem, PA",
    description:
      "A tired front yard reimagined with new plant beds, clean edging, and a welcoming layout.",
    before: {
      src: "/images/gallery/landscape-design-bethlehem-pa-before.svg",
      alt: "Plain front yard before landscape design in Bethlehem PA",
      width: W,
      height: H,
    },
    after: {
      src: "/images/gallery/landscape-design-bethlehem-pa-after.svg",
      alt: "Redesigned front yard with new plant beds and edging in Bethlehem PA",
      width: W,
      height: H,
    },
    featured: true,
  },
  {
    id: "shrub-removal-bethlehem",
    title: "Old Shrub Removal in Bethlehem",
    category: "cleanup",
    location: "Bethlehem, PA",
    description:
      "Overgrown foundation shrubs torn out and hauled away for a clean, fresh start.",
    before: {
      src: "/images/gallery/shrub-removal-bethlehem-pa-before.svg",
      alt: "Overgrown foundation shrubs before removal in Bethlehem PA",
      width: W,
      height: H,
    },
    after: {
      src: "/images/gallery/shrub-removal-bethlehem-pa-after.svg",
      alt: "Clean foundation line after shrub and yard debris removal in Bethlehem PA",
      width: W,
      height: H,
    },
  },
  {
    id: "storm-cleanup-lehigh-valley",
    title: "Storm Debris Cleanup After a Lehigh Valley Storm",
    category: "cleanup",
    location: "Lehigh Valley, PA",
    description:
      "Downed limbs and storm debris cleared quickly to make the property safe again.",
    before: {
      src: "/images/gallery/storm-cleanup-bethlehem-pa-before.svg",
      alt: "Yard covered in downed limbs and storm debris in the Lehigh Valley",
      width: W,
      height: H,
    },
    after: {
      src: "/images/gallery/storm-cleanup-bethlehem-pa-after.svg",
      alt: "Cleared and safe yard after storm debris cleanup in the Lehigh Valley",
      width: W,
      height: H,
    },
  },
  {
    id: "tree-trimming-bethlehem",
    title: "Tree Trimming & Shaping in Bethlehem",
    category: "tree-removal",
    location: "Bethlehem, PA",
    description:
      "Mature trees trimmed and shaped, with branches cleared away from the roofline.",
    after: {
      src: "/images/gallery/tree-trimming-bethlehem-pa-after.svg",
      alt: "Neatly trimmed and shaped mature trees after pruning in Bethlehem PA",
      width: W,
      height: H,
    },
  },
  {
    id: "lawn-care-bethlehem",
    title: "Lawn Care & Cleanup in Bethlehem",
    category: "landscape-design",
    location: "Bethlehem, PA",
    description:
      "Freshly mowed, edged, and cleaned-up lawn maintained through the season.",
    after: {
      src: "/images/gallery/lawn-care-bethlehem-pa-after.svg",
      alt: "Freshly mowed and edged green lawn after lawn care in Bethlehem PA",
      width: W,
      height: H,
    },
  },
];

export function getFeaturedItems(): GalleryItem[] {
  return galleryItems.filter((i) => i.featured);
}

export function itemsByCategory(category: string): GalleryItem[] {
  if (category === "all") return galleryItems;
  return galleryItems.filter((i) => i.category === category);
}
